- Update GHA workflow

diff --git a/.github/workflows/docker-build-release.yml b/.github/workflows/docker-build-release.yml
--- a/.github/workflows/docker-build-release.yml
+++ b/.github/workflows/docker-build-release.yml
@@ -1,16 +1,22 @@
-name: docker-build-release
+name: build-release
 
 on:
+  pull_request:
+    types: [ opened, synchronize, reopened, closed ]
+    branches:
+      - main
+      - master
   push:
     branches:
-      - dev
       - main
       - master
     tags:
       - 'v*'
 
 env:
-  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
+  APP_NAME: rubix-bacnet
+  GHCR_IMAGE: ghcr.io/nubeio/rubix-bacnet
+  PLATFORMS: linux/amd64,linux/arm/v7
 
 jobs:
 
@@ -18,45 +24,41 @@ jobs:
     runs-on: ubuntu-latest
 
     outputs:
-      name: ${{ steps.grep.outputs.name }}
-      version: ${{ steps.grep.outputs.cVer }}
-      sha: ${{ steps.grep.outputs.sha }}
-      fqn: ${{ steps.grep.outputs.name }}-${{ steps.grep.outputs.cVer }}-${{ steps.grep.outputs.sha }}
-      images: ${{ steps.docker_image_name.outputs.images }}
-      isRelease: ${{ steps.grep.outputs.isRelease }}
+      shouldBuild: ${{ steps.context.outputs.decision_build }}
+      shouldPublish: ${{ steps.context.outputs.decision_publish }}
+      isRelease: ${{ steps.context.outputs.isTag }}
+      afterRelease: ${{ steps.context.outputs.isAfterMergedReleasePR }}
+      sha: ${{ steps.context.outputs.commitId }}
+      version: ${{ steps.context.outputs.version }}
+      fqn: ${{ env.APP_NAME }}-${{ steps.context.outputs.version }}-${{ steps.context.outputs.shortCommitId }}
 
     steps:
       - uses: actions/checkout@v2
+        with:
+          token: ${{ secrets.NUBEIO_CI_GITHUBPROJECT_TOKEN }}
 
-      - name: Grep project
-        id: grep
-        shell: bash
-        run: |
-          echo ::set-output name=name::$(head -n 5 pyproject.toml | grep name | cut -d ":" -f2 | grep -oP "(?<=\")([^\"]+)(?=\")")
-          echo ::set-output name=cVer::$(head -n 5 pyproject.toml | grep version | cut -d ":" -f2 | grep -oP "(?<=\")([^\"]+)(?=\")")
-          echo ::set-output name=version::$(echo "${{ github.ref }}" | sed -e "s#^refs/tags/v##")
-          echo ::set-output name=sha::$(git rev-parse --short ${{ github.sha }})
-          echo ::set-output name=isRelease::${{ startsWith(github.ref, 'refs/tags/v') }}
+      - name: Import GPG key
+        uses: crazy-max/ghaction-import-gpg@v3
+        with:
+          git-user-signingkey: true
+          git-commit-gpgsign: true
+          git-tag-gpgsign: true
+          git-push-gpgsign: false
+          gpg-private-key: ${{ secrets.NUBEIO_CI_GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.NUBEIO_CI_GPG_PASSPHARSE }}
 
-      - name: Validate version
-        if: ${{ steps.grep.outputs.isRelease == 'true' }}
-        run: |
-          echo "Should Validate Version with semantic..."
-          echo "Project name: ${{ steps.grep.outputs.name }}"
-          echo "Current version: ${{ steps.grep.outputs.cVer }}"
-          echo "Target version: ${{ steps.grep.outputs.version }}"
-          [[ ${{ steps.grep.outputs.cVer }} == ${{ steps.grep.outputs.version }} ]] || { echo "Release version and tag version is not match"; exit 1; }
-
-      - name: Docker image name
-        id: docker_image_name
-        run: |
-          localRegistry=localhost:5000/${{ steps.grep.outputs.name }}
-          ghcr=ghcr.io/nubeio/${{ steps.grep.outputs.name }}
-          dockerHub=nubeio/${{ steps.grep.outputs.name }}
-          echo ::set-output name=images::$ghcr
+      - name: Project context
+        id: context
+        uses: zero88/gh-project-context@v1
+        with:
+          dry: false
+          mustSign: true
+          defaultBranch: master
 
   build:
     runs-on: ubuntu-latest
+    needs: context
+    if: needs.context.outputs.shouldBuild == 'true'
     services:
       registry:
         image: zero88/gh-registry:latest
@@ -65,7 +67,6 @@ jobs:
         options: >-
           -v /home/runner:/var/lib/registry
           --name registry
-    needs: context
     steps:
       - uses: actions/checkout@v2
 
@@ -82,13 +83,13 @@ jobs:
 
       - name: Validate cache
         run: |
-          docker buildx imagetools inspect localhost:5000/${{ needs.context.outputs.name }}:buildcache || echo "Not Found"
+          docker buildx imagetools inspect localhost:5000/${{ env.APP_NAME }}:buildcache || echo "Not Found"
 
       - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
-          images: ${{ needs.context.outputs.images }}
+          images: ${{ env.GHCR_IMAGE }}
           tag-latest: true
           tag-sha: true
           tag-semver: |
@@ -114,16 +115,16 @@ jobs:
             BASE_IMAGE_VERSION=3.9
             APP_VERSION=${{ needs.context.outputs.version }}
             COMMIT_SHA=${{ needs.context.outputs.sha }}
-          cache-from: type=registry,ref=localhost:5000/${{ needs.context.outputs.name }}:buildcache
-          cache-to: type=registry,ref=localhost:5000/${{ needs.context.outputs.name }}:buildcache,mode=max
-          tags: localhost:5000/${{ needs.context.outputs.name }}:${{ needs.context.outputs.sha }}
+          cache-from: type=registry,ref=localhost:5000/${{ env.APP_NAME }}:buildcache
+          cache-to: type=registry,ref=localhost:5000/${{ env.APP_NAME }}:buildcache,mode=max
+          tags: localhost:5000/${{ env.APP_NAME }}:${{ needs.context.outputs.sha }}
           pull: true
           push: true
 
       - name: Zip artifacts
         if: ${{ needs.context.outputs.isRelease == 'true' }}
         run: |
-          image=localhost:5000/${{ needs.context.outputs.name }}:${{ needs.context.outputs.sha }}
+          image=localhost:5000/${{ env.APP_NAME }}:${{ needs.context.outputs.sha }}
           output=/usr/src/app/
           mkdir -p /tmp/zip /tmp/images
           IFS=',' read -ra ARR <<< "${{ env.PLATFORMS }}"
@@ -142,7 +143,7 @@ jobs:
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
-          password: ${{ secrets.NUBEIO_CI_GITHUBPACKAGE_TOKEN }}
+          password: ${{ secrets.NUBEIO_CI_GITHUB_PACKAGES_PAT }}
 
       - name: Docker build
         uses: docker/build-push-action@v2
@@ -154,8 +155,8 @@ jobs:
             BASE_IMAGE_VERSION=3.9
             APP_VERSION=${{ needs.context.outputs.version }}
             COMMIT_SHA=${{ needs.context.outputs.sha }}
-          cache-from: type=registry,ref=localhost:5000/${{ needs.context.outputs.name }}:buildcache
-          cache-to: type=registry,ref=localhost:5000/${{ needs.context.outputs.name }}:buildcache,mode=max
+          cache-from: type=registry,ref=localhost:5000/${{ env.APP_NAME }}:buildcache
+          cache-to: type=registry,ref=localhost:5000/${{ env.APP_NAME }}:buildcache,mode=max
           tags: ${{ steps.docker_meta.outputs.tags }}
           labels: ${{ steps.docker_meta.outputs.labels }}
           pull: true
@@ -163,7 +164,7 @@ jobs:
 
       - name: Cleanup Docker build cache if any
         run: |
-          docker buildx imagetools inspect localhost:5000/${{ needs.context.outputs.name }}:buildcache
+          docker buildx imagetools inspect localhost:5000/${{ env.APP_NAME }}:buildcache
           echo "======================================================"
           docker buildx prune --filter until=72h --keep-storage 5GB -f
 
